apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: prometheus-operator-grafana
  namespace: default
spec:
  ports:
  - name: service
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: grafana
    release: prometheus-operator
  type: NodePort
